name: Python CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        task: [lint, typecheck, test]

    name: ${{ matrix.task }} on Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          make install-test

      - name: Run ${{ matrix.task }}
        run: |
          case "${{ matrix.task }}" in
            lint)
              make black
              ;;
            typecheck)
              make mypy
              ;;
            test)
              make coverage
              ;;
          esac
